### ISSUE TITLE
LICEcap

### ISSUE THREAD

**Issue by ComFreek** [jsturtevant/chocolatey-recipe#1]
I was searching for an existent LICEcap package before creating my own and I found your note [`# need to create my own`](https://github.com/jsturtevant/chocolatey-recipe/blob/master/chocolatey-recipe.txt#L43).
I've created such a package and contacted the maintainers to see if they would like to take over/maintain that package: http://forum.cockos.com/showthread.php?t=152673

**Comment by jsturtevant** [comment]
Thanks! looks like the package is now avaliable at https://chocolatey.org/packages/licecap
